<?php
//echo '<pre>';
//print_r((get_class_methods($this->form->get('title'))));
//print_r((()));
//die();

$title = 'Edit Album :'. $this->form->get('title')->getValue();
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<?php

$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album Title');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', [
    'action'=>'edit',
    'id' => $id,
]));

$this->form->prepare();

//echo $this->form()->openTag($form);
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($album); ?>
    <?= $this->formElement($album); ?>
    <?= $this->formElementErrors()->render( $album, ['class'=>  'help-block']); ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist); ?>
    <?= $this->formElement($artist); ?>
    <?= $this->formElementErrors()->render( $artist, ['class'=>  'help-block']); ?>
</div>

<?php

echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();



